import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import grid from "@styles/grid.module.scss";

import ProtectedRoute from "@components/ProtectedRoute";
import StoreProvider from "./components/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "BaristaGadgets",
	description: "Generated by BaristaGadgets",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<StoreProvider>
					<ProtectedRoute>
						<div className={grid.container}>{children}</div>
					</ProtectedRoute>
				</StoreProvider>
			</body>
		</html>
	);
}
