import type { Metadata } from "next";
import { Barlow } from "next/font/google";

import "@styles/globals.scss";
import "@styles/variables.scss";
import styles from "@styles/grid.module.scss";

import Navbar from "@components/Navbar/Navbar";
import ProtectedRoute from "@components/ProtectedRoute";
import StoreProvider from "@components/StoreProvider";

const BarlowFont = Barlow({ subsets: ["latin"], weight: ["200", "400", "600", "700", "900"] });

export const metadata: Metadata = {
	title: "BaristaGadgets",
	description: "Generated by BaristaGadgets",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={BarlowFont.className}>
				<StoreProvider>
					<ProtectedRoute>
						<div className={styles.layout__container}>
							<Navbar />
							{children}
						</div>
					</ProtectedRoute>
				</StoreProvider>
			</body>
		</html>
	);
}
